version: '3'

services:
  strapi:
    build: .
    restart: always
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - .:/srv/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./postgres_data:/srv/app
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - 5432:5432